-- Copyright https://www.red-gate.com/simple-talk/databases/postgresql/saving-data-historically-with-temporal-tables-part-1-queries/

-- Table example
create table emp (
  emp_no int primary key,
  name text,
  salary int,
  project text);

-- Schema
drop schema if exists temp_agg cascade;
create schema temp_agg;

-- Temporal table
create table emp_temporal (
   emp_no int,
   name text,
   salary int,
   project text,
   emp_row_id bigint  not null primary key
       generated by default as identity,
   emp_ts timestamptz,
   emp_te timestamptz
);

-- Querying Temporal Databases
Create view emp_current as
  select emp_no, name, salary, project,
         emp_row_id, emp_ts, emp_te
  from emp_temporal
  where emp_ts <=current_timestamp
    and current_timestamp < emp_te;

--
select emp_no, name, project, salary
from emp_temporal
where  emp_ts <= '2023-06-12'::timestamptz
   and '2023-06-12'::timestamptz < emp_te;
